export const ADD_STATE = 'ADD_STATE';
export const ADD_STATE_SUCCESS = 'ADD_STATE_SUCCESS';
export const ADD_STATE_ERROR = 'ADD_STATE_ERROR';

export const DELETE_STATE = 'DELETE_STATE'; 
export const DELETE_STATE_SUCCESS = 'DELETE_STATE_SUCCESS';
export const DELETE_STATE_ERROR = 'DELETE_STATE_ERROR';

export const GET_ALL_STATES = 'GET_ALL_STATES';
export const GET_ALL_STATES_SUCCESS = 'GET_ALL_STATES_SUCCESS';
export const GET_ALL_STATES_ERROR = 'GET_ALL_STATES_ERROR'
