export const BLOOD_DONOR_REGISTER='BLOOD_DONOR_REGISTER'
export const BLOOD_DONOR_REGISTER_SUCCESS = 'BLOOD_DONOR_REGISTER_SUCCESS'
export const BLOOD_DONOR_REGISTER_ERROR = 'BLOOD_DONOR_REGISTER_ERROR'