export const ADD_AREA = 'ADD_AREA';
export const ADD_AREA_SUCCESS = 'ADD_AREA_SUCCESS';
export const ADD_AREA_ERROR = 'ADD_AREA_ERROR';

export const DELETE_AREA = 'DELETE_AREA';
export const DELETE_AREA_SUCCESS = 'DELETE_AREA_SUCCESS';
export const DELETE_AREA_ERROR = 'DELETE_AREA_ERROR';

export const GET_ALL_AREAS = 'GET_ALL_AREAS';
export const GET_ALL_AREAS_SUCCESS = 'GET_ALL_AREAS_SUCCESS';
export const GET_ALL_AREAS_ERROR = 'GET_ALL_AREAS_ERROR';