export const BLOOD_RECIPIENT_REGISTER = 'BLOOD_RECIPIENT_REGISTER';
export const BLOOD_RECIPIENT_REGISTER_SUCCESS = 'BLOOD_RECIPIENT_REGISTER_SUCCESS';
export const BLOOD_RECIPIENT_REGISTER_ERROR = 'BLOOD_RECIPIENT_REGISTER_ERROR';