export const BLOOD_RECIPIENT_REGISTER = 'BLOOD_RECIPIENT_REGISTER';
export const BLOOD_RECIPIENT_REGISTER_SUCCESS = 'BLOOD_RECIPIENT_REGISTER_SUCCESS';
export const BLOOD_RECIPIENT_REGISTER_ERROR = 'BLOOD_RECIPIENT_REGISTER_ERROR';
export const BLOOD_RECIPIENT_FIND_ALL = 'BLOOD_RECIPIENT_FIND_ALL';
export const BLOOD_RECIPIENT_FIND_ALL_SUCCESS = 'BLOOD_RECIPIENT_FIND_ALL_SUCCESS';
export const BLOOD_RECIPIENT_FIND_ALL_ERROR = 'BLOOD_RECIPIENT_FIND_ALL_ERROR';