export const ADD_COUNTRY = 'ADD_COUNTRY';
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS';
export const ADD_COUNTRY_ERROR = 'ADD_COUNTRY_ERROR';

export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS';
export const DELETE_COUNTRY_ERROR = 'DELETE_COUNTRY_ERROR';

export const VIEW_COUNTRY = 'VIEW_COUNTRY';
export const VIEW_COUNTRY_SUCCESS = 'VIEW_COUNTRY_SUCCESS';
export const VIEW_COUNTRY_ERROR = 'VIEW_COUNTRY_ERROR';